### ISSUE TITLE
Seperate dev dependecies from dependencies

### ISSUE THREAD

**Issue by heartistizio** [Tay0108/cracow-transit-front#45]
We are bundling way too much stuff, hmu if you want some help with that.

![obraz](https://user-images.githubusercontent.com/20524370/114915661-1ef02d00-9e24-11eb-86aa-52afc2b3331d.png)
![obraz](https://user-images.githubusercontent.com/20524370/114915685-28799500-9e24-11eb-9998-464681f10b1f.png)
profit

**Comment by Tay0108** [comment]
Heroku doesn't install dev dependencies, are you aware of that?

**Comment by heartistizio** [comment]
It does, it just prunes them. So you need to add a build stage that builds the app and then run it with whatever you need.

**Comment by Tay0108** [comment]
Ok, then I guess we can try it out ;)
